import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";
import { useGetPostsQuery } from "../hook";
import { wrapper } from "../store";
import { postApi } from "../postApi";

const Home: NextPage = () => {
  const { data: posts } = useGetPostsQuery();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          {posts?.map((post) => (
            <a
              href="https://nextjs.org/docs"
              className={styles.card}
              key={post.id}
            >
              <h2>{post.title} &rarr;</h2>
              <p>{post.body}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async () => {
    store.dispatch(postApi.endpoints.getPosts.initiate());

    await Promise.all(postApi.util.getRunningOperationPromises());
    return {
      props: {},
    };
  }
);
